### ISSUE TITLE
Role seed missing

### ISSUE THREAD

**Issue by fidalgo** [Solutionize/Phoenix#2]
There's a missing seed: the Roles

```

bundle exec rake state_zone_city:seed_all                                  
States data seed successful
Zones data seed successful
Cities data seed successful
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Role can't be blank
```

from file `02_state_zone_centre.rake:92`

**Comment by goravbhootra** [comment]
@fidalgo Can you try running `rake db:drop db:create db:migrate db:seed`

Just tried it and everything is working fine:

> Currencies data seed successful
> States data seed successful
> Zones data seed successful
> Cities data seed successful
> Users data seed successful
> Languages seed successful
> Categories seed successful

`Role.count`

> => 5

Roles are getting created in `20150620200735_accounts_related.rb`. I will move them to rake task later.
